DROP TABLE admin CASCADE CONSTRAINTS PURGE;
DROP TABLE benefit CASCADE CONSTRAINTS PURGE;
DROP TABLE certification CASCADE CONSTRAINTS PURGE;
DROP TABLE district CASCADE CONSTRAINTS PURGE;
DROP TABLE employee CASCADE CONSTRAINTS PURGE;
DROP TABLE ot_pay CASCADE CONSTRAINTS PURGE;
DROP TABLE other_emp CASCADE CONSTRAINTS PURGE;
DROP TABLE pab_item CASCADE CONSTRAINTS PURGE;
DROP TABLE pab_lineitem CASCADE CONSTRAINTS PURGE;
DROP TABLE reg_pay CASCADE CONSTRAINTS PURGE;
DROP TABLE teacher CASCADE CONSTRAINTS PURGE;
DROP TABLE teacher_cert_int CASCADE CONSTRAINTS PURGE;
DROP TABLE total_pab CASCADE CONSTRAINTS PURGE;


CREATE TABLE EMPLOYEE (
    DISTRICT_ID CHAR(5 BYTE) NOT NULL,
    EMP_ID CHAR(5 BYTE) NOT NULL,
    EMP_FNAME CHAR(50 BYTE) NULL,
    EMP_LNAME CHAR(50 BYTE) NOT NULL,
    ZIPCODE CHAR(50 BYTE) NULL,
    HIREDATE DATE DEFAULT SYSDATE NULL,
    PREVIOUS_EXPERIENCE_YEARS NUMBER(3, 1) DEFAULT 0 NULL,
    HIGHEST_EARNED_DEGREE CHAR(11 BYTE) DEFAULT 'Bachelor' NULL, 
    DIRECT_ADMIN_ID CHAR(5 BYTE) NULL,
    IS_ADMIN CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
    IS_TEACHER CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    EDU_EMAIL VARCHAR2(20 BYTE) NOT NULL,
    CONSTRAINT EMPLOYEE_UK1 UNIQUE ( EDU_EMAIL ),
    CONSTRAINT EMPLOYEE_PK1 PRIMARY KEY ( EMP_ID ),
    CONSTRAINT EMPLOYEE_EDU_EMAIL_CHECK CHECK ((UPPER(EDU_EMAIL) LIKE '_%_@_%_._%_.EDU')),
    CONSTRAINT EMPLOYEE_HIGHEST_EARNED_DEGREE_CHECK CHECK ( HIGHEST_EARNED_DEGREE IN ( 'GRE',
    'High School', 'Associate', 'Bachelor', 'Master', 'Doctorate' ) ),
    CONSTRAINT EMPLOYEE_HIREDATE_CHECK CHECK ( HIREDATE >= DATE '1950-01-01')
);
CREATE TABLE ADMIN (
    A_EMP_ID CHAR(5 BYTE) NOT NULL,
    ADMIN_START_DATE DATE DEFAULT SYSDATE NOT NULL,
    ADMIN_END_DATE DATE NULL,
    DIVERSITY_TRAINING_CERT CHAR(1 BYTE) DEFAULT 'N' NOT NULL,
    ADMIN_TITLE CHAR(40 BYTE) NULL,
    CONSTRAINT ADMIN_PK PRIMARY KEY ( A_EMP_ID ),
    CONSTRAINT ADMIN_FK1 FOREIGN KEY ( A_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID ),
    CONSTRAINT ADMIN_DIVERSITY_TRAINING_CERT_CHECK CHECK ( DIVERSITY_TRAINING_CERT IN ( 'Y', 'N') ),
    CONSTRAINT ADMIN_ADMIN_END_DATE_CHECK CHECK ( ADMIN_END_DATE >= ADMIN_START_DATE )
);
CREATE TABLE TEACHER (
    T_EMP_ID CHAR(5 BYTE) NOT NULL,
    IS_FULLTIME CHAR(1 BYTE) DEFAULT 'Y' NOT NULL,
    GRADE_OR_SPECIAL CHAR(1 BYTE) DEFAULT 'G' NOT NULL,
    CONSTRAINT TEACHER_PK PRIMARY KEY ( T_EMP_ID ),
    CONSTRAINT TEACHER_FK1 FOREIGN KEY ( T_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID ),
    CONSTRAINT TEACHER_GRADE_OR_SPECIAL_CHECK CHECK ( GRADE_OR_SPECIAL IN ('G', 'S'))
);
CREATE TABLE OTHER_EMP (
    O_EMP_ID CHAR(5 BYTE) NOT NULL,
    TYPE CHAR(30 BYTE) NOT NULL,
    TITLE CHAR(50 BYTE) NULL,
    CONSTRAINT OTHER_EMP_PK PRIMARY KEY ( O_EMP_ID ),
    CONSTRAINT OTHER_EMP_FK1 FOREIGN KEY ( O_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID ),
    CONSTRAINT OTHER_EMP_TYPE_CHECK CHECK (TYPE IN ( 'CUSTODIAL', 'SECURITY', 'COUNSELING',
    'CONSTRUCT', 'LANDSCAPING', 'UNCATEGORIZED' ))
);
CREATE TABLE CERTIFICATION (
    CERT_ID CHAR(5 BYTE) NOT NULL,
    STATE_CERT_CODE CHAR(10 BYTE) NOT NULL,
    CERT_DESC VARCHAR2(100 BYTE) NULL,
    CONSTRAINT CERTIFICATION_UK1 UNIQUE ( STATE_CERT_CODE ),
    CONSTRAINT CERTIFICATION_PK PRIMARY KEY ( CERT_ID )
);
CREATE TABLE TEACHER_CERT_INT (
    T_EMP_ID CHAR(5 BYTE) NOT NULL,
    CERT_ID CHAR(5 BYTE) NOT NULL,
    DATE_EFFECTIVE DATE NOT NULL,
    DATE_EXPIRES DATE NULL,
    CONSTRAINT TEACHER_CERT_INT_PK PRIMARY KEY ( T_EMP_ID,
    CERT_ID,
    DATE_EFFECTIVE ),
    CONSTRAINT TEACHER_CERT_INT_FK1 FOREIGN KEY ( T_EMP_ID )
    REFERENCES TEACHER ( T_EMP_ID ),
    CONSTRAINT TEACHER_CERT_INT_FK2 FOREIGN KEY ( CERT_ID )
    REFERENCES CERTIFICATION ( CERT_ID )
);
CREATE TABLE DISTRICT (
    DISTRICT_ID CHAR(5 BYTE) NOT NULL,
    DISTRICT_NAME VARCHAR2(100 BYTE) NOT NULL,
    SUPERINTENDENT_ID CHAR(5 BYTE) NULL,
    CONSTRAINT DISTRICT_UK1 UNIQUE ( SUPERINTENDENT_ID ),
    CONSTRAINT DISTRICT_PK PRIMARY KEY ( DISTRICT_ID ),
    CONSTRAINT DISTRICT_FK1 FOREIGN KEY ( SUPERINTENDENT_ID )
    REFERENCES ADMIN ( A_EMP_ID )
);
CREATE TABLE TOTAL_PAB (
    EMP_ID CHAR(5) NOT NULL,
    TAX_YEAR NUMBER(4, 0) NOT NULL,
    REG_PAY NUMBER(7, 0) NULL,
    OVERTIME_PAY NUMBER(7, 0) NULL,
    OTHER_PAY NUMBER(7, 0) NULL,
    TOTAL_BENEFITS NUMBER(7, 0) NULL,
    DATE_LAST_CALC DATE NULL,
    PAB_ID CHAR(5) NOT NULL,
    REVIEW_ADMIN_ID CHAR(5) NULL,
    CONSTRAINT TOTAL_PAB_UK1 UNIQUE ( EMP_ID,
    TAX_YEAR ),
    CONSTRAINT TOTAL_PAB_PK1 PRIMARY KEY ( PAB_ID ),
    CONSTRAINT TOTAL_PAB_FK1 FOREIGN KEY ( EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID ),
    CONSTRAINT TOTAL_PAB_FK2 FOREIGN KEY ( REVIEW_ADMIN_ID )
    REFERENCES ADMIN ( A_EMP_ID )
);
CREATE TABLE PAB_ITEM (
    PAB_ITEM_ID CHAR(5) NOT NULL,
    TYPE CHAR(15) NOT NULL,
    ITEM_DESC VARCHAR2(100) NOT NULL,
    CONSTRAINT PAB_ITEM_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT PAB_ITEM_TYPE_CHECK CHECK ( TYPE IN ( 'REGULAR PAY', 'OVERTIME PAY',
    'OTHER PAY', 'BENEFIT' ) )
);
CREATE TABLE BENEFIT (
    PAB_ITEM_ID CHAR(5) NOT NULL,
    TAXABLE_CODE_ID CHAR(10) NOT NULL,
    CONSTRAINT BENEFIT_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT BENEFIT_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);
CREATE TABLE OT_PAY (
    PAB_ITEM_ID CHAR(5) NOT NULL,
    HOLIDAY_MULTIPLIER NUMBER(4, 2) NOT NULL,
    CONSTRAINT OT_PAY_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT OT_PAY_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID ),
    CONSTRAINT HOLIDAY_MULTIPLIER_CHECK CHECK ( HOLIDAY_MULTIPLIER BETWEEN ( 1.00 )
    AND ( 3.50 ) )
);
CREATE TABLE REG_PAY (
    PAB_ITEM_ID CHAR(5) NOT NULL,
    COLLECTIVE_BARGAINING_SECT CHAR(15) NOT NULL,
    CONSTRAINT REG_PAY_PK PRIMARY KEY ( PAB_ITEM_ID ),
    CONSTRAINT REG_PAY_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);
CREATE TABLE PAB_LINEITEM (
    PAB_ID CHAR(5) NOT NULL,
    PAB_ITEM_ID CHAR(5) NOT NULL,
    BEG_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    AMOUNT_POSTED NUMBER(9, 2) DEFAULT 0 NOT NULL,
    POSTED_TIMESTAMP TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PAB_LINEITEM_PK PRIMARY KEY ( PAB_ITEM_ID,
    PAB_ID,
    BEG_DATE,
    END_DATE ),
    CONSTRAINT PAB_LINEITEM_FK FOREIGN KEY ( PAB_ID )
    REFERENCES TOTAL_PAB ( PAB_ID ),
    CONSTRAINT PAB_LINEITEM_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID )
);
ALTER TABLE ADMIN
    DROP CONSTRAINT ADMIN_FK1;
ALTER TABLE TEACHER
    DROP CONSTRAINT TEACHER_FK1;
ALTER TABLE OTHER_EMP
    DROP CONSTRAINT OTHER_EMP_FK1;
ALTER TABLE TEACHER_CERT_INT
    DROP CONSTRAINT TEACHER_CERT_INT_FK1;
ALTER TABLE TEACHER_CERT_INT
    DROP CONSTRAINT TEACHER_CERT_INT_FK2;
ALTER TABLE DISTRICT
    DROP CONSTRAINT DISTRICT_FK1;
ALTER TABLE TOTAL_PAB
    DROP CONSTRAINT TOTAL_PAB_FK1;
ALTER TABLE TOTAL_PAB
    DROP CONSTRAINT TOTAL_PAB_FK2;
ALTER TABLE BENEFIT
    DROP CONSTRAINT BENEFIT_FK1;
ALTER TABLE OT_PAY
    DROP CONSTRAINT OT_PAY_FK1;
ALTER TABLE REG_PAY
    DROP CONSTRAINT REG_PAY_FK1;
ALTER TABLE PAB_LINEITEM
    DROP CONSTRAINT PAB_LINEITEM_FK;
ALTER TABLE PAB_LINEITEM
    DROP CONSTRAINT PAB_LINEITEM_FK1;
    
ALTER TABLE EMPLOYEE
    ADD CONSTRAINT EMPLOYEE_FK1 FOREIGN KEY ( DIRECT_ADMIN_ID )
    REFERENCES ADMIN ( A_EMP_ID );
ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_FK FOREIGN KEY ( DISTRICT_ID )
    REFERENCES DISTRICT ( DISTRICT_ID );
ALTER TABLE ADMIN
    ADD CONSTRAINT ADMIN_FK1 FOREIGN KEY ( A_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID );
ALTER TABLE TEACHER
    ADD CONSTRAINT TEACHER_FK1 FOREIGN KEY ( T_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID );
ALTER TABLE OTHER_EMP
    ADD CONSTRAINT OTHER_EMP_FK1 FOREIGN KEY ( O_EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID );
ALTER TABLE TEACHER_CERT_INT
    ADD CONSTRAINT TEACHER_CERT_INT_FK1 FOREIGN KEY ( T_EMP_ID )
    REFERENCES TEACHER ( T_EMP_ID );
ALTER TABLE TEACHER_CERT_INT
    ADD CONSTRAINT TEACHER_CERT_INT_FK2 FOREIGN KEY ( CERT_ID )
    REFERENCES CERTIFICATION ( CERT_ID );
ALTER TABLE DISTRICT
    ADD CONSTRAINT DISTRICT_FK1 FOREIGN KEY ( SUPERINTENDENT_ID )
    REFERENCES ADMIN ( A_EMP_ID );
ALTER TABLE TOTAL_PAB
    ADD CONSTRAINT TOTAL_PAB_FK1 FOREIGN KEY ( EMP_ID )
    REFERENCES EMPLOYEE ( EMP_ID );
ALTER TABLE TOTAL_PAB
    ADD CONSTRAINT TOTAL_PAB_FK2 FOREIGN KEY ( REVIEW_ADMIN_ID )
    REFERENCES ADMIN ( A_EMP_ID );
ALTER TABLE BENEFIT
    ADD CONSTRAINT BENEFIT_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID );
ALTER TABLE OT_PAY
    ADD CONSTRAINT OT_PAY_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID );
ALTER TABLE REG_PAY
    ADD CONSTRAINT REG_PAY_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID );
ALTER TABLE PAB_LINEITEM
    ADD CONSTRAINT PAB_LINEITEM_FK FOREIGN KEY ( PAB_ID )
    REFERENCES TOTAL_PAB ( PAB_ID );
ALTER TABLE PAB_LINEITEM
    ADD CONSTRAINT PAB_LINEITEM_FK1 FOREIGN KEY ( PAB_ITEM_ID )
    REFERENCES PAB_ITEM ( PAB_ITEM_ID );